[package]
name = "mini-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
term_size = "0.3.2"

[dev-dependencies]
tempfile = "3"
